name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2.0.0
        with:
          github-token: ${{ github.token }}
          issue-labels: 'off-topic'
          issue-comment: 'This repository does not accept issues, see the README for more details.'
          skip-closed-issue-comment: true
          pr-comment: 'This repository does not accept pull requests, see the README for more details.'
          skip-closed-pr-comment: true
